### ISSUE TITLE
Question: How do you implement iframes instead of popups?

### ISSUE THREAD

**Issue by thevinci** [Vestorly/torii#286] opened 2016-03-30 19:05 UTC
I believed that I followed the directions on the readme to the point and cannot seem to get it working. I noticed that the npm install version of 0.6.1 didn't have iframe.js or iframe template. I went ahead and pulled the github one directly into my package.json. I think since I used the recent version of Ember, I didn't need to use the initializer. Then I tried to start the {{torii-iframe-placeholder}} everywhere to no avail. Am I missing something here?

**Comment by denzo** [comment] 2016-03-30 22:25
Questions should go on StackOverflow :)

**Comment by balinterdi** [comment] 2016-06-17 13:34
This still doesn't seem to work with Torii 0.8.0. In my `config/environment.js`, I have:

```js
    torii: {
      sessionServiceName: 'session',
      remoteServiceName: 'iframe',
      providers: {
        (...)
      }
    }
```

And I have the iframe placeholder in my application template:

```hbs
<div class="container">
  <div class="row">
    {{torii-iframe-placeholder}}
    {{outlet}}
  </div>
</div>
```

**Comment by balinterdi** [comment] 2016-06-17 13:37
Ok, I made progress by moving the iframe to the provider-specific block:

```js
    torii: {
      sessionServiceName: 'session',
      providers: {
        'google-oauth2-bearer': {
          remoteServiceName: 'iframe',
          (...)
        }
      }
    }
```

I know get the following error when initiating authorization:

> Refused to display 'https://accounts.google.com/AccountChooser?continue=https://accounts.google….com%26from_login%3D1%26as%3D-759f9f28e8d3768b&btmpl=authsub&scc=1&oauth=1' in a frame because it set 'X-Frame-Options' to 'DENY'.

but I guess the latter is not a Torii bug.

However, taking my cue from [the README](https://github.com/Vestorly/torii#using-an-iframe-instead-of-a-popup) the global `iframe` settings should also work.

**Comment by kellyselden** [comment] 2016-06-26 02:19
@balinterdi Confirmed that it works differently when moved to the provider hash. Doesn't work at all when used globally.

**Comment by balinterdi** [comment] 2016-07-21 19:45
So playing around with this a little more it seems like Google does not allow the OAuth authorization flow to be carried out in an iframe. I tried [this "hack"](http://stackoverflow.com/questions/20498831/refused-to-display-in-a-frame-because-it-set-x-frame-options-to-sameorigin) and it did not work.

I then stumbled upon [this old Google group post](https://groups.google.com/forum/#!topic/twitter-development-talk/DrgtdqU0EN8) that advises against doing OAuth in an iframe. Not sure they are authoritative resources but it certainly seems like it is not allowed with Google. Not sure about other providers.

**Comment by bantic** [comment] 2016-07-22 17:57
Thanks for the update. Yes, the fact that `remoteServiceName` in the general torii config doesn't work but it does work for specific provider configs is a bug.

Regarding google and the x-frame-options header, I think that you're right; it's not possible to open a torii provider in an iframe if the source site forbids it...

I'm going to close this issue and open a separate to specifically address the bug mentioned above. Please reopen if I've missed anything.

**Closed by bantic** 2016-07-22 17:57 UTC
